name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - name: Install stable rust
      run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      name: Cache dependencies
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
